import React from 'react'

export const AboutUs = () => {
  return (
    <div className="mt-8">
    <h3 className="font-medium mx-20 my-10 text-2xl text-blue-500">¿Quienes somos?</h3>
        <p className="mx-20 font-light text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga adipisci quas dolorum aspernatur         at quasi esse voluptate maxime cupiditate nam explicabo numquam aut libero architecto eligendi, dicta obcaecati eaque ex!         Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque itaque optio placeat reprehenderit, vel eligendi, ducimus         temporibus illo molestias consectetur ratione tenetur? Eius delectus tempora vitae cupiditate repellat, iusto corrupti?         Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia officiis quisquam aspernatur eius id unde, amet         reiciendis harum beatae. Natus dolores dicta suscipit cupiditate neque in. Laborum pariatur aut doloribus. Lorem ipsum         dolor, sit amet consectetur adipisicing elit. Aspernatur soluta tempora corrupti veniam inventore, eligendi, recusandae         atque odit cupiditate adipisci architecto quod? Deleniti fugit optio animi, sit voluptatem omnis nobis!</p>
        <h4 className="mx-20 mt-16 text-xl font-medium text-blue-500">Objetivos</h4>
            <p className="my-5 mx-20  text-sm font-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque laborum modi voluptatum assumenda cum earum tempora animi. Dolores non unde, quam dolorem, magni culpa iste voluptates voluptatum porro earum eum. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores voluptatum nam, aliquid reprehenderit laudantium aliquam tempora, qui id maxime consequatur voluptatem cupiditate sapiente odit repudiandae optio praesentium laborum! Nulla, neque?</p>
            <p className="my-5 mx-20 text-sm font-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, odit. Voluptatem ducimus laudantium debitis eveniet nemo harum quis provident eum eos rerum, aliquam aut! Nam repellendus vel corrupti in quod. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora obcaecati veniam voluptas in, ipsam dolor, laudantium consectetur molestiae qui soluta fugiat earum porro cupiditate quo quam accusamus ullam ducimus dicta?</p>
            <p className="my-5 mx-20 text-sm font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero voluptas molestias dicta delectus ipsa animi excepturi velit quidem odit reprehenderit, tempora in ea perferendis, placeat temporibus, id doloribus fuga? Quibusdam? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur aliquam natus veniam impedit autem nisi eveniet ipsam praesentium eos ex porro inventore, quos dignissimos voluptas a ab molestias quibusdam necessitatibus?</p>
            <p className="my-5 mx-20 text-sm font-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi quae dolor veritatis ipsum provident quia alias laboriosam perspiciatis natus tempore, magni officia repellendus minima incidunt est assumenda aliquam cupiditate. Aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus minus hic vero est, labore inventore beatae? Distinctio nulla pariatur officia harum, officiis quasi, molestias corrupti nostrum reprehenderit at, eligendi ullam!</p>
    </div>
  )
}
